// <auto-generated />
namespace Drugstore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Precursor_AddnewTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Precursor_AddnewTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181824097_Precursor_AddnewTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
