// <auto-generated />
namespace Drugstore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MedicinalSubstance_Added_new_OTM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MedicinalSubstance_Added_new_OTM));
        
        string IMigrationMetadata.Id
        {
            get { return "202102171535061_MedicinalSubstance_Added_new_OTM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
